# TCL File Generated by Component Editor 21.1
# Tue May 13 11:36:48 EDT 2025
# DO NOT MODIFY


# 
# codec_interface "CODEC" v1.0
#  2025.05.13.11:36:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module codec_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME codec_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME CODEC
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL codec_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Altera_UP_Audio_Bit_Counter.v VERILOG PATH Audio/codec_interface/Altera_UP_Audio_Bit_Counter.v
add_fileset_file Altera_UP_Audio_In_Deserializer.v VERILOG PATH Audio/codec_interface/Altera_UP_Audio_In_Deserializer.v
add_fileset_file Altera_UP_Audio_Out_Serializer.v VERILOG PATH Audio/codec_interface/Altera_UP_Audio_Out_Serializer.v
add_fileset_file Altera_UP_Clock_Edge.v VERILOG PATH Audio/codec_interface/Altera_UP_Clock_Edge.v
add_fileset_file Altera_UP_I2C.v VERILOG PATH Audio/codec_interface/Altera_UP_I2C.v
add_fileset_file Altera_UP_I2C_AV_Auto_Initialize.v VERILOG PATH Audio/codec_interface/Altera_UP_I2C_AV_Auto_Initialize.v
add_fileset_file Altera_UP_I2C_DC_Auto_Initialize.v VERILOG PATH Audio/codec_interface/Altera_UP_I2C_DC_Auto_Initialize.v
add_fileset_file Altera_UP_I2C_LCM_Auto_Initialize.v VERILOG PATH Audio/codec_interface/Altera_UP_I2C_LCM_Auto_Initialize.v
add_fileset_file Altera_UP_SYNC_FIFO.v VERILOG PATH Audio/codec_interface/Altera_UP_SYNC_FIFO.v
add_fileset_file Altera_UP_Slow_Clock_Generator.v VERILOG PATH Audio/codec_interface/Altera_UP_Slow_Clock_Generator.v
add_fileset_file audio_and_video_config.v VERILOG PATH Audio/codec_interface/audio_and_video_config.v
add_fileset_file audio_codec.v VERILOG PATH Audio/codec_interface/audio_codec.v
add_fileset_file clock_generator.v VERILOG PATH Audio/codec_interface/clock_generator.v
add_fileset_file codec_interface.sv SYSTEM_VERILOG PATH Audio/codec_interface/codec_interface.sv TOP_LEVEL_FILE
add_fileset_file xck_generator.cmp OTHER PATH Audio/codec_interface/xck_generator.cmp
add_fileset_file xck_generator.sip OTHER PATH Audio/codec_interface/xck_generator.sip
add_fileset_file xck_generator.spd OTHER PATH Audio/codec_interface/xck_generator.spd
add_fileset_file xck_generator.v VERILOG PATH Audio/codec_interface/xck_generator.v
add_fileset_file xck_generator_0002.qip OTHER PATH Audio/codec_interface/xck_generator/xck_generator_0002.qip
add_fileset_file xck_generator_0002.v VERILOG PATH Audio/codec_interface/xck_generator/xck_generator_0002.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLOCK_50 clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point driver_codec_interface
# 
add_interface driver_codec_interface conduit end
set_interface_property driver_codec_interface associatedClock clock
set_interface_property driver_codec_interface associatedReset ""
set_interface_property driver_codec_interface ENABLED true
set_interface_property driver_codec_interface EXPORT_OF ""
set_interface_property driver_codec_interface PORT_NAME_MAP ""
set_interface_property driver_codec_interface CMSIS_SVD_VARIABLES ""
set_interface_property driver_codec_interface SVD_ADDRESS_GROUP ""

add_interface_port driver_codec_interface advance advance Output 1
add_interface_port driver_codec_interface dac_left leftsample Input 24
add_interface_port driver_codec_interface dac_right rightsample Input 24


# 
# connection point audio
# 
add_interface audio conduit end
set_interface_property audio associatedClock clock
set_interface_property audio associatedReset ""
set_interface_property audio ENABLED true
set_interface_property audio EXPORT_OF ""
set_interface_property audio PORT_NAME_MAP ""
set_interface_property audio CMSIS_SVD_VARIABLES ""
set_interface_property audio SVD_ADDRESS_GROUP ""

add_interface_port audio AUD_ADCDAT aud_adcdat Input 1
add_interface_port audio AUD_ADCLRCK aud_adclrck Input 1
add_interface_port audio AUD_BCLK aud_bclk Input 1
add_interface_port audio AUD_DACDAT aud_dacdat Output 1
add_interface_port audio AUD_DACLRCK aud_daclrck Input 1
add_interface_port audio AUD_XCK aud_xck Output 1
add_interface_port audio FPGA_I2C_SCLK fpga_i2c_sclk Output 1
add_interface_port audio FPGA_I2C_SDAT fpga_i2c_sdat Bidir 1


# 
# connection point Open
# 
add_interface Open conduit end
set_interface_property Open associatedClock clock
set_interface_property Open associatedReset ""
set_interface_property Open ENABLED true
set_interface_property Open EXPORT_OF ""
set_interface_property Open PORT_NAME_MAP ""
set_interface_property Open CMSIS_SVD_VARIABLES ""
set_interface_property Open SVD_ADDRESS_GROUP ""

add_interface_port Open adc_left adc_left Output 24
add_interface_port Open adc_right adc_right Output 24

